name: cowin_api
version: 0.0.1
description: COWIN API Client
environment:
    sdk: '>=2.7.0 <3.0.0'
dependencies:
    dio: ^3.0.9
    built_value: '>=7.1.0 <8.0.0'
    built_collection: '>=4.3.2 <5.0.0'
dev_dependencies:
    built_value_generator: '>=7.1.0 <8.0.0'
    build_runner: ^1.7.1
    test: '>=1.3.0 <1.16.0'
# The following was added as per https://github.com/dart-lang/sdk/issues/44421
dependency_overrides:
  analyzer: ^0.41.1
